apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: print-message-
spec:
  entrypoint: echo
  templates:
  - name: echo
    script:
      image: alpine:3.20.0
      command: ["/bin/sh"]
      source: echo "Hello World"