apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webhook-event-source
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  webhook:
    pod:
      port: "12000"
      endpoint: /pod-creation
      method: POST