apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: github-
  namespace: playground
spec:
  arguments:
    parameters:
    - name: apiToken
    - name: owner
      value: argoproj
    - name: repo
      value: argo-workflows
  serviceAccountName: playground-sa
  entrypoint: main
  templates:
  - name: main
    inputs:
      parameters:
      - name: apiToken
      - name: owner
      - name: repo
    dag:
      tasks:
      - name: get-repo-branches
        arguments:
          parameters:
          - name: apiToken
            value: "{{ inputs.parameters.apiToken }}"
          - name: owner
            value: "{{ inputs.parameters.owner }}"
          - name: repo
            value: "{{ inputs.parameters.repo }}"
        template: github-request
      - name: parse-branch-names
        arguments:
          parameters:
          - name: json-response
            value: "{{ tasks.get-repo-branches.outputs.result }}"
        template: parse-branch-names
        dependencies: [get-repo-branches]
  - name: github-request
    inputs:
      parameters:
      - name: apiToken
      - name: owner
      - name: repo
    http:
      url: "https://api.github.com/repos/{{inputs.parameters.owner}}/{{inputs.parameters.repo}}/branches?per_page=2"
      method: "GET"
      headers:
      - name: "Accept"
        value: "application/vnd.github+json"
      - name: "Authorization"
        value: "Bearer {{inputs.parameters.apiToken}}"
      - name: "X-GitHub-Api-Version"
        value: "2022-11-28"
      successCondition: response.statusCode == 200
  - name: parse-branch-names
    inputs:
      parameters:
      - name: json-response
    script:
      image: nicolaka/netshoot:v0.13
      command: ["/bin/sh"]
      source: |
        echo '{{ inputs.parameters.json-response }}' | jq '.[].name'