apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: parallel-data-processing-
spec:
  arguments:
    parameters:
      - name: json-data
        value: |
          [
             {"date": "2024-03-01", "size": 100},
             {"date": "2024-05-20", "size": 531},
             {"date": "2024-07-04", "size": 999},
             {"date": "2024-10-22", "size": 13}
          ]

  entrypoint: worker

  templates:
  - name: worker
    parallelism: 2
    inputs:
      parameters:
        - name: json-data
    steps:
    - - name: processing
        template: json-parsing
        arguments:
          parameters:
            - name: data-item
              value: "{{item}}"
        withParam: "{{inputs.parameters.json-data}}"

  - name: json-parsing
    inputs:
      parameters:
        - name: data-item
    container:
      image: bmuschko/bash-jq:1.0.0
      args: ["-c", "echo '{{inputs.parameters.data-item}}' | jq '.size'"]