apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
spec:
  entrypoint: hello-world

  templates:
  - name: hello-world
    container:
      image: alpine:3.19.1
      command: [echo]
      args: ["Hello World!"]