apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: rollouts-apisix-route
spec:
  http:
    - name: rollouts-apisix
      match:
        paths:
          - /*
        methods:
          - GET
          - POST
          - PUT
          - DELETE
          - PATCH
        hosts:
          - canary-rollout.local
      backends:
        - serviceName: nginx-stable-service
          servicePort: 80
        - serviceName: nginx-canary-service
          servicePort: 80