apiVersion: traefik.containo.us/v1alpha1
kind: TraefikService
metadata:
  name: traefik-service
spec:
  weighted:
    services:
      - name: nginx-stable-service
        port: 80
      - name: nginx-canary-service
        port: 80