apiVersion: v1
kind: Namespace
metadata:
  name: workflow-exec
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: workflow-exec-sa
  namespace: workflow-exec
secrets:
- apiVersion: v1
  kind: Secret
  name: workflow-exec-sa-token
  namespace: workflow-exec
---
apiVersion: v1
kind: Secret
metadata:
  name: workflow-exec-sa-token
  namespace: workflow-exec
  annotations:
    kubernetes.io/service-account.name: workflow-exec-sa
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workflow-exec-rb
  namespace: workflow-exec
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: workflow-exec-sa
  namespace: workflow-exec
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: agent
  namespace: workflow-exec
rules:
- apiGroups:
  - argoproj.io
  resources:
  - workflowtasksets
  verbs:
  - list
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - workflowtasksets/status
  verbs:
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workflow-exec-rb-argo
  namespace: workflow-exec
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: agent
subjects:
- kind: ServiceAccount
  name: workflow-exec-sa
  namespace: workflow-exec
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: read-secret-cr
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  resourceNames:
  - argo-workflows-agent-ca-certificates
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-read-secret
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: read-secret-cr
subjects:
- kind: ServiceAccount
  name: argo
  namespace: argo