apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: print-message-
spec:
  entrypoint: main
  templates:
  - name: main
    steps:
    - - name: echo
        arguments:
          parameters:
          - name: message
            value: "{{ item }}"
        template: echo
        withItems:
        - a
        - b
        - c
  - name: echo
    inputs:
      parameters:
      - name: message
    script:
      image: alpine:3.20.0
      command: ["/bin/sh"]
      source: echo "{{ inputs.parameters.message }}"