apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: print-message-
spec:
  arguments:
    parameters:
    - name: messages
      value: '["a", "b", "c"]'
  entrypoint: main
  templates:
  - name: main
    inputs:
      parameters:
      - name: messages
    steps:
    - - name: echo
        arguments:
          parameters:
          - name: message
            value: "{{ item }}"
        template: echo
        withParam: "{{ inputs.parameters.messages }}"
  - name: echo
    inputs:
      parameters:
      - name: message
    script:
      image: alpine:3.20.0
      command: ["/bin/sh"]
      source: echo "{{ inputs.parameters.message }}"